services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=request-system
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: